// @ts-check
// Config generated by @nuxt/eslint module during `nuxt prepare`.
// Extend it here with any project-specific overrides.
import { withNuxt } from './.nuxt/eslint.config.mjs'

export default withNuxt().append({
  rules: {
    // Ideographic spaces (U+3000) are intentional in JLPT question text.
    'no-irregular-whitespace': 'off',
  },
})
